/* hello.ash.h: generated by ashc emit-header, do not edit.
 * Every layout these names describe comes from ash/ash_abi.h; include
 * that header for the value and descriptor structs. */
#ifndef ASH_HEADER_HELLO
#define ASH_HEADER_HELLO

/* contract Greeter, version 1
 * vow prefix: String (default)
 */
#define ASH_HASH_Greeter 0x80464bf23398ab38ULL

/* pledge greet(name: String) -> Result<String, GreetError> */
#define ASH_MANGLED_Greeter_greet "__ash_ash_Greeter_greet_17cef80f14421b9b_v1"

/* pledge shout(name: String) -> Result<String, GreetError>, abstract */
#define ASH_MANGLED_Greeter_shout "__ash_ash_Greeter_shout_17cef80f14421b9b_v1"

#endif /* ASH_HEADER_HELLO */
