/* hello.geas.h: generated by geas emit-header, do not edit.
 * Every layout these names describe comes from geas/geas_abi.h; include
 * that header for the value and descriptor structs. */
#ifndef GEAS_HEADER_HELLO
#define GEAS_HEADER_HELLO

/* contract Greeter, version 1
 * vow prefix: String (default)
 */
#define GEAS_HASH_Greeter 0x80464bf23398ab38ULL

/* pledge greet(name: String) -> Result<String, GreetError> */
#define GEAS_MANGLED_Greeter_greet "__geas_ash_Greeter_greet_17cef80f14421b9b_v1"

/* pledge shout(name: String) -> Result<String, GreetError>, abstract */
#define GEAS_MANGLED_Greeter_shout "__geas_ash_Greeter_shout_17cef80f14421b9b_v1"

#endif /* GEAS_HEADER_HELLO */
