// Code generated by ashc emit-proto from payment.ash. DO NOT EDIT.
//
// The session wrapper for TypeScript over @grpc/grpc-js and
// @grpc/proto-loader: load the .proto beside this file at runtime, take
// the service client it yields, and open a session here. protoc's typed
// stubs fit where a build step is welcome; this wrapper leans on the
// loader instead, so a host like an editor extension ships no native
// code and no generated stubs. Load with keepCase: true, longs: String,
// and oneofs: true: the field names keep the wire's own snake_case, and
// every 64 bit integer, the instance id and the hash first among them,
// crosses as a decimal string, which is how the interfaces below spell
// them. The syntax stays inside the erasable set, so node runs this
// file directly under type stripping, no compiler in the loop.

// The shape of the call a session opens, the one surface the wrapper
// needs from grpc-js, spelled structurally so nothing is imported.
export interface SessionStream {
  on(event: "data", listener: (ev: unknown) => void): unknown;
  on(event: "error", listener: (err: Error) => void): unknown;
  cancel(): void;
}

// PaymentServiceShapeHash is the contract's shape hash, the same value the
// compiled module registers. Sending its decimal spelling as expected_hash
// pins the wire to this build; leaving the field unset skips the check.
export const PaymentServiceShapeHash: bigint = 0xc4261f5e32ecf727n;

export interface PaymentServiceSignRequest {
  currency?: string;  // the vow; unset takes the declared default
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface PaymentServiceSigned {
  instance_id: string;
  currency: string;
  shape_hash: string;
  signed_at: string;
}

// PaymentServiceSession holds a signed instance open. The instance lives
// exactly as long as this handle: close ends the stream, and the server
// breaks and drops the instance.
export interface PaymentServiceSession {
  signed: PaymentServiceSigned;
  close(): void;
}

// openPaymentServiceSession signs the contract and holds the session stream.
// The signature is read off the stream before the promise settles, so the
// caller holds a live, addressable instance or an error, never a maybe.
export function openPaymentServiceSession(
  client: { Session(req: PaymentServiceSignRequest): SessionStream },
  req: PaymentServiceSignRequest,
): Promise<PaymentServiceSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Session(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: PaymentServiceSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      // After the signature the stream's end is the session's end, the
      // cancel the close asked for; before it, the sign itself refused.
      if (!opened) { reject(err); }
    });
  });
}
