// Code generated by ashc emit-proto from payment.ash. DO NOT EDIT.
//
// The session wrapper. protoc gives a consumer every typed pledge call;
// this file gives the one thing it cannot, the stream whose lifetime is
// the instance's. Opening a session signs and reads the signature; the
// handle's Close ends the stream, and the server breaks and drops the
// instance. It lives in the same package as the protoc output, so the
// two halves of the surface import as one.
package paymentpb

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
)

// PaymentServiceShapeHash is the contract's shape hash, the same value the
// compiled module registers. A SignRequest carrying it pins the wire to
// this build; 0 skips the check.
const PaymentServiceShapeHash uint64 = 0xc4261f5e32ecf727

// PaymentServiceSession holds a signed instance open. The instance lives
// exactly as long as this handle: Close ends the stream, and the server
// breaks and drops the instance.
type PaymentServiceSession struct {
	Signed *Signed
	cancel context.CancelFunc
	stream grpc.ServerStreamingClient[SessionEvent]
}

// OpenPaymentServiceSession signs the contract and holds the session stream.
// The signature is read off the stream before this returns, so the caller
// holds a live, addressable instance or an error, never a maybe.
func OpenPaymentServiceSession(ctx context.Context, c PaymentServiceClient, req *SignRequest) (
	*PaymentServiceSession, error,
) {
	sctx, cancel := context.WithCancel(ctx)
	stream, err := c.Session(sctx, req)
	if err != nil {
		cancel()
		return nil, err
	}
	ev, err := stream.Recv()
	if err != nil {
		cancel()
		return nil, err
	}
	signed := ev.GetSigned()
	if signed == nil {
		cancel()
		return nil, fmt.Errorf("the session stream opened with %v, not the signature", ev)
	}
	return &PaymentServiceSession{Signed: signed, cancel: cancel, stream: stream}, nil
}

// Close ends the session; the server breaks the instance and drops it.
func (s *PaymentServiceSession) Close() { s.cancel() }
