// Code generated by ashc emit-proto from std_user.ash. DO NOT EDIT.
//
// The session wrapper. protoc gives a consumer every typed pledge call;
// this file gives the one thing it cannot, the stream whose lifetime is
// the instance's. Opening a session signs and reads the signature; the
// handle's Close ends the stream, and the server breaks and drops the
// instance. It lives in the same package as the protoc output, so the
// two halves of the surface import as one.
package std_userpb

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
)

// IntGateShapeHash is the contract's shape hash, the same value the
// compiled module registers. A SignRequest carrying it pins the wire to
// this build; 0 skips the check.
const IntGateShapeHash uint64 = 0xf442daee47750a14

// IntGateSession holds a signed instance open. The instance lives
// exactly as long as this handle: Close ends the stream, and the server
// breaks and drops the instance.
type IntGateSession struct {
	Signed *IntGateSigned
	cancel context.CancelFunc
	stream grpc.ServerStreamingClient[IntGateSessionEvent]
}

// OpenIntGateSession signs the contract and holds the session stream.
// The signature is read off the stream before this returns, so the caller
// holds a live, addressable instance or an error, never a maybe.
func OpenIntGateSession(ctx context.Context, c IntGateClient, req *IntGateSignRequest) (
	*IntGateSession, error,
) {
	sctx, cancel := context.WithCancel(ctx)
	stream, err := c.Session(sctx, req)
	if err != nil {
		cancel()
		return nil, err
	}
	ev, err := stream.Recv()
	if err != nil {
		cancel()
		return nil, err
	}
	signed := ev.GetSigned()
	if signed == nil {
		cancel()
		return nil, fmt.Errorf("the session stream opened with %v, not the signature", ev)
	}
	return &IntGateSession{Signed: signed, cancel: cancel, stream: stream}, nil
}

// Close ends the session; the server breaks the instance and drops it.
func (s *IntGateSession) Close() { s.cancel() }

// StdUserShapeHash is the contract's shape hash, the same value the
// compiled module registers. A SignRequest carrying it pins the wire to
// this build; 0 skips the check.
const StdUserShapeHash uint64 = 0xff920d047d909132

// StdUserSession holds a signed instance open. The instance lives
// exactly as long as this handle: Close ends the stream, and the server
// breaks and drops the instance.
type StdUserSession struct {
	Signed *StdUserSigned
	cancel context.CancelFunc
	stream grpc.ServerStreamingClient[StdUserSessionEvent]
}

// OpenStdUserSession signs the contract and holds the session stream.
// The signature is read off the stream before this returns, so the caller
// holds a live, addressable instance or an error, never a maybe.
func OpenStdUserSession(ctx context.Context, c StdUserClient, req *StdUserSignRequest) (
	*StdUserSession, error,
) {
	sctx, cancel := context.WithCancel(ctx)
	stream, err := c.Session(sctx, req)
	if err != nil {
		cancel()
		return nil, err
	}
	ev, err := stream.Recv()
	if err != nil {
		cancel()
		return nil, err
	}
	signed := ev.GetSigned()
	if signed == nil {
		cancel()
		return nil, fmt.Errorf("the session stream opened with %v, not the signature", ev)
	}
	return &StdUserSession{Signed: signed, cancel: cancel, stream: stream}, nil
}

// Close ends the session; the server breaks the instance and drops it.
func (s *StdUserSession) Close() { s.cancel() }

// MathOpsShapeHash is the contract's shape hash, the same value the
// compiled module registers. A SignRequest carrying it pins the wire to
// this build; 0 skips the check.
const MathOpsShapeHash uint64 = 0x0e9c63abf058a12e

// MathOpsSession holds a signed instance open. The instance lives
// exactly as long as this handle: Close ends the stream, and the server
// breaks and drops the instance.
type MathOpsSession struct {
	Signed *MathOpsSigned
	cancel context.CancelFunc
	stream grpc.ServerStreamingClient[MathOpsSessionEvent]
}

// OpenMathOpsSession signs the contract and holds the session stream.
// The signature is read off the stream before this returns, so the caller
// holds a live, addressable instance or an error, never a maybe.
func OpenMathOpsSession(ctx context.Context, c MathOpsClient, req *MathOpsSignRequest) (
	*MathOpsSession, error,
) {
	sctx, cancel := context.WithCancel(ctx)
	stream, err := c.Session(sctx, req)
	if err != nil {
		cancel()
		return nil, err
	}
	ev, err := stream.Recv()
	if err != nil {
		cancel()
		return nil, err
	}
	signed := ev.GetSigned()
	if signed == nil {
		cancel()
		return nil, fmt.Errorf("the session stream opened with %v, not the signature", ev)
	}
	return &MathOpsSession{Signed: signed, cancel: cancel, stream: stream}, nil
}

// Close ends the session; the server breaks the instance and drops it.
func (s *MathOpsSession) Close() { s.cancel() }

// ListOpsShapeHash is the contract's shape hash, the same value the
// compiled module registers. A SignRequest carrying it pins the wire to
// this build; 0 skips the check.
const ListOpsShapeHash uint64 = 0xd1fa13d356232e92

// ListOpsSession holds a signed instance open. The instance lives
// exactly as long as this handle: Close ends the stream, and the server
// breaks and drops the instance.
type ListOpsSession struct {
	Signed *ListOpsSigned
	cancel context.CancelFunc
	stream grpc.ServerStreamingClient[ListOpsSessionEvent]
}

// OpenListOpsSession signs the contract and holds the session stream.
// The signature is read off the stream before this returns, so the caller
// holds a live, addressable instance or an error, never a maybe.
func OpenListOpsSession(ctx context.Context, c ListOpsClient, req *ListOpsSignRequest) (
	*ListOpsSession, error,
) {
	sctx, cancel := context.WithCancel(ctx)
	stream, err := c.Session(sctx, req)
	if err != nil {
		cancel()
		return nil, err
	}
	ev, err := stream.Recv()
	if err != nil {
		cancel()
		return nil, err
	}
	signed := ev.GetSigned()
	if signed == nil {
		cancel()
		return nil, fmt.Errorf("the session stream opened with %v, not the signature", ev)
	}
	return &ListOpsSession{Signed: signed, cancel: cancel, stream: stream}, nil
}

// Close ends the session; the server breaks the instance and drops it.
func (s *ListOpsSession) Close() { s.cancel() }
