// Code generated by ashc emit-proto from std_user.ash. DO NOT EDIT.
//
// The session wrapper for TypeScript over @grpc/grpc-js and
// @grpc/proto-loader: load the .proto beside this file at runtime, take
// the service client it yields, and open a session here. protoc's typed
// stubs fit where a build step is welcome; this wrapper leans on the
// loader instead, so a host like an editor extension ships no native
// code and no generated stubs. Load with keepCase: true, longs: String,
// and oneofs: true: the field names keep the wire's own snake_case, and
// every 64 bit integer, the instance id and the hash first among them,
// crosses as a decimal string, which is how the interfaces below spell
// them. The syntax stays inside the erasable set, so node runs this
// file directly under type stripping, no compiler in the loop.

// The shape of the call a session opens, the one surface the wrapper
// needs from grpc-js, spelled structurally so nothing is imported.
export interface SessionStream {
  on(event: "data", listener: (ev: unknown) => void): unknown;
  on(event: "error", listener: (err: Error) => void): unknown;
  cancel(): void;
}

// IntGateShapeHash is the contract's shape hash, the same value the
// compiled module registers. Sending its decimal spelling as expected_hash
// pins the wire to this build; leaving the field unset skips the check.
export const IntGateShapeHash: bigint = 0xf442daee47750a14n;

export interface IntGateSignRequest {
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface IntGateResumeRequest {
  park_token: string;  // the resume key a park enabled server issued at sign
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface IntGateSigned {
  instance_id: string;
  shape_hash: string;
  signed_at: string;
  park_token: string;  // empty when the server runs without a park store
}

// IntGateSession holds a signed instance open. The instance lives
// exactly as long as this handle: close ends the stream, and the server
// breaks and drops the instance.
export interface IntGateSession {
  signed: IntGateSigned;
  close(): void;
}

// openIntGateSession signs the contract and holds the session stream.
// The signature is read off the stream before the promise settles, so the
// caller holds a live, addressable instance or an error, never a maybe.
export function openIntGateSession(
  client: { Session(req: IntGateSignRequest): SessionStream },
  req: IntGateSignRequest,
): Promise<IntGateSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Session(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: IntGateSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      // After the signature the stream's end is the session's end, the
      // cancel the close asked for; before it, the sign itself refused.
      if (!opened) { reject(err); }
    });
  });
}

// resumeIntGateSession stands a parked instance back up and holds its new
// session stream, the same handle open answers; close is once again the
// ending.
export function resumeIntGateSession(
  client: { Resume(req: IntGateResumeRequest): SessionStream },
  req: IntGateResumeRequest,
): Promise<IntGateSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Resume(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: IntGateSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      if (!opened) { reject(err); }
    });
  });
}

// StdUserShapeHash is the contract's shape hash, the same value the
// compiled module registers. Sending its decimal spelling as expected_hash
// pins the wire to this build; leaving the field unset skips the check.
export const StdUserShapeHash: bigint = 0xff920d047d909132n;

export interface StdUserSignRequest {
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface StdUserResumeRequest {
  park_token: string;  // the resume key a park enabled server issued at sign
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface StdUserSigned {
  instance_id: string;
  shape_hash: string;
  signed_at: string;
  park_token: string;  // empty when the server runs without a park store
}

// StdUserSession holds a signed instance open. The instance lives
// exactly as long as this handle: close ends the stream, and the server
// breaks and drops the instance.
export interface StdUserSession {
  signed: StdUserSigned;
  close(): void;
}

// openStdUserSession signs the contract and holds the session stream.
// The signature is read off the stream before the promise settles, so the
// caller holds a live, addressable instance or an error, never a maybe.
export function openStdUserSession(
  client: { Session(req: StdUserSignRequest): SessionStream },
  req: StdUserSignRequest,
): Promise<StdUserSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Session(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: StdUserSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      // After the signature the stream's end is the session's end, the
      // cancel the close asked for; before it, the sign itself refused.
      if (!opened) { reject(err); }
    });
  });
}

// resumeStdUserSession stands a parked instance back up and holds its new
// session stream, the same handle open answers; close is once again the
// ending.
export function resumeStdUserSession(
  client: { Resume(req: StdUserResumeRequest): SessionStream },
  req: StdUserResumeRequest,
): Promise<StdUserSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Resume(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: StdUserSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      if (!opened) { reject(err); }
    });
  });
}

// MathOpsShapeHash is the contract's shape hash, the same value the
// compiled module registers. Sending its decimal spelling as expected_hash
// pins the wire to this build; leaving the field unset skips the check.
export const MathOpsShapeHash: bigint = 0x0e9c63abf058a12en;

export interface MathOpsSignRequest {
  epsilon?: number;  // the vow; unset takes the declared default
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface MathOpsResumeRequest {
  park_token: string;  // the resume key a park enabled server issued at sign
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface MathOpsSigned {
  instance_id: string;
  epsilon: number;
  shape_hash: string;
  signed_at: string;
  park_token: string;  // empty when the server runs without a park store
}

// MathOpsSession holds a signed instance open. The instance lives
// exactly as long as this handle: close ends the stream, and the server
// breaks and drops the instance.
export interface MathOpsSession {
  signed: MathOpsSigned;
  close(): void;
}

// openMathOpsSession signs the contract and holds the session stream.
// The signature is read off the stream before the promise settles, so the
// caller holds a live, addressable instance or an error, never a maybe.
export function openMathOpsSession(
  client: { Session(req: MathOpsSignRequest): SessionStream },
  req: MathOpsSignRequest,
): Promise<MathOpsSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Session(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: MathOpsSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      // After the signature the stream's end is the session's end, the
      // cancel the close asked for; before it, the sign itself refused.
      if (!opened) { reject(err); }
    });
  });
}

// resumeMathOpsSession stands a parked instance back up and holds its new
// session stream, the same handle open answers; close is once again the
// ending.
export function resumeMathOpsSession(
  client: { Resume(req: MathOpsResumeRequest): SessionStream },
  req: MathOpsResumeRequest,
): Promise<MathOpsSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Resume(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: MathOpsSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      if (!opened) { reject(err); }
    });
  });
}

// ListOpsShapeHash is the contract's shape hash, the same value the
// compiled module registers. Sending its decimal spelling as expected_hash
// pins the wire to this build; leaving the field unset skips the check.
export const ListOpsShapeHash: bigint = 0xd1fa13d356232e92n;

export interface ListOpsSignRequest {
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface ListOpsResumeRequest {
  park_token: string;  // the resume key a park enabled server issued at sign
  expected_hash?: string;  // a decimal uint64; the shape hash's toString() pins
}

export interface ListOpsSigned {
  instance_id: string;
  shape_hash: string;
  signed_at: string;
  park_token: string;  // empty when the server runs without a park store
}

// ListOpsSession holds a signed instance open. The instance lives
// exactly as long as this handle: close ends the stream, and the server
// breaks and drops the instance.
export interface ListOpsSession {
  signed: ListOpsSigned;
  close(): void;
}

// openListOpsSession signs the contract and holds the session stream.
// The signature is read off the stream before the promise settles, so the
// caller holds a live, addressable instance or an error, never a maybe.
export function openListOpsSession(
  client: { Session(req: ListOpsSignRequest): SessionStream },
  req: ListOpsSignRequest,
): Promise<ListOpsSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Session(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: ListOpsSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      // After the signature the stream's end is the session's end, the
      // cancel the close asked for; before it, the sign itself refused.
      if (!opened) { reject(err); }
    });
  });
}

// resumeListOpsSession stands a parked instance back up and holds its new
// session stream, the same handle open answers; close is once again the
// ending.
export function resumeListOpsSession(
  client: { Resume(req: ListOpsResumeRequest): SessionStream },
  req: ListOpsResumeRequest,
): Promise<ListOpsSession> {
  return new Promise((resolve, reject) => {
    const stream = client.Resume(req);
    let opened = false;
    stream.on("data", (ev) => {
      if (opened) { return; }
      const signed = (ev as { signed?: ListOpsSigned }).signed;
      if (!signed) {
        stream.cancel();
        reject(new Error("the session stream opened without the signature"));
        return;
      }
      opened = true;
      resolve({ signed, close: () => stream.cancel() });
    });
    stream.on("error", (err) => {
      if (!opened) { reject(err); }
    });
  });
}
